stages:
  - install-environment
  - test
  - build

test-n-build-urbano:
  stage: install-environment
  script:
    - export GO_VERSION=1.6.1
    - export PROJECT=urbanobot
    - rm -rf $HOME/golang
    - rm -rf $(pwd)/src
    - mkdir -p $HOME/golang # for GOROOT (contains the Go binary & core packages)
    - mkdir -p $HOME/gopath/src/gitlab.com/iarenzana/${PROJECT} # for GOPATH (contains code and external packages)
    - curl http://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz 2>/dev/null > go${GO_VERSION}.linux-amd64.tar.gz
    - tar -C $HOME/golang -xzf go${GO_VERSION}.linux-amd64.tar.gz
    - export GOROOT=$HOME/golang/go
    - export GOPATH=$HOME/gopath
    - export PATH=$PATH:$GOROOT/bin
    - export PATH=$PATH:$GOPATH/bin
    - (if [[ "$(go version)" == *"go version go${GO_VERSION}"* ]]; then echo "✓ Go binary installed!"; else echo "Go binary not installed"; exit -1; fi);
    - cp -r /builds/iarenzana/urbanobot ${GOPATH}/src/gitlab.com/iarenzana/.
    - cd ${GOPATH}/src/gitlab.com/iarenzana/${PROJECT}
    - go get
#
#	Test
#
    - go test
#
#	Build
#
    - pwd
    - go build

  only:
    - master
